name: "ucode ci/cd pipeline"

on:
  push:
    branches: ["feat/*"]
  pull_request:
    branches: ["master"]

defaults:
  run:
    shell: bash

jobs:
  
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd backend
          make install-dev
          make test

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd frontend
          npm install
          npm run test:unit

  build:
    name: "Build all containers"
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    steps:
      - uses: actions/checkout@v3
      - name: Try to build containers
        run: docker compose build

  build-and-deploy:
    runs-on: [self-hosted, linux, ucode]
    if: ${{ github.event_name != 'pull_request' }}
    needs: build
    steps:
      - name: List currently running containers
        run: docker compose ps

      - name: Stop running containers and delete volumes
        run: docker compose down --volumes

      - uses: actions/checkout@v3

      - name: (Re)build containers
        run: docker compose build

      - name: Start newly built containers in detached mode
        run: docker compose up --detach
